.github/workflows/ci.yml, tests/apps/verify-ppb/pyproject.toml, tests/apps/verify-pyside6/pyproject.toml, tests/apps/verify-toga/pyproject.toml
This should fix CI by adding missing required info
- [] All new features have been documented
=> Add missing pyproject.toml data

{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}/Main.cpp
Modifications to the VisualStudio template to support testing.
This is primarily adding support for the BRIEFCASE_MAIN_MODULE testing override; if the environment contains that environment variable, it will be used in preference to the app's default module name.
It also disables optimisation (this conflicts with pytest, and generally seems to be unnecessary), and slightly reorders the code on exit to ensure that SystemExit doesn't get printed as a stack trace.
It also removes the redirection from stdout/stderr to CONOUT$ when there is an attached console. This redirection appears to be unnecessary as long as stdout/stderr is flushed, and was the cause of beeware/briefcase#787 (as well as being an impediment to filtering logs for testing purposes).
Refs beeware/briefcase#962
Fixes …
=> Add support for BRIEFCASE_MAIN_MODULE testing entry point.

{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}/Main.cpp
For some reason, the Windows `Main(String [] args)` *doesn't* set `args[0]` to the name of the executable.
This PR modifies the argc/argv passed to Python to include this extra argument.
Refs beeware/briefcase#1078.
=> Ensure argv[0] has the executable name.

{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}/CrashDialog.h, {{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}/Main.cpp, {{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.vcxproj
During app startup, there appears to be an implicit call to set the Winforms threading model. This causes problems on Qt, which makes it's own call to set the threading model as part of app startup.
This adds a call to uninitialise the threading model at startup, ensuring that app-specific attempts to set the threading model 
won't cause a crash.
This doesn't appear to impact the operation of the Crash Dialog, or Toga's own Dialog behaviour (Toga sets STA mode during app startup). The sample program provided by beeware/briefcase#930 also appears to work.
Also cleans up some environment management code that was raising warnings about using "unsafe" versions of methods.
Huge thanks to @davidfokkema for the leg work leading to this PR.
This could/should be backported to 0.3.12; it will also …
=> Uninitialize the threading model during app startup.

cookiecutter.json, {{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
There is now a new option `use_full_install_path` which defaults to `True` to install the application in `Programs/<author name>/<app name>`. If you include the option in the `pyproject.toml` with a value of `False`, it installs the application into `Programs/<app name>`.
See beeware/briefcase#1199 and beeware/briefcase-windows-app-template#11.
=> Optionally include author in installation path

{{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
- Before version 2.2.0, `True`/`False` values were exposed as strings
- Now, they are the actual `True` and `False` symbols
=> Add support for cookiecutter>=2.2.0

{{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/settings.manifest, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.vcxproj
This allows Toga to determine the actual Windows version within `briefcase run`. It already works within `briefcase dev`, because then it's using the manifest of python.exe.
=> Add manifest file

.github/workflows/ci.yml
- The underlying API to download this Python is no longer available to GitHub runners
- RE: https://github.com/beeware/.github/pull/65
=> Remove Windows Store Python testing from CI

cookiecutter.json, {{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/Main.cpp, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.vcxproj
Adds support for console apps in Visual Studio projects.
This involves:
* Modifying the stub executable code to *not* perform the stdout/logger redirection used by GUI apps
* Link the stub binary against the Console system rather than the Windows subsystem
* Outputting `app-name.exe` rather than `Formal Name.exe`
* Modifying the MSI installer to add the installation path to the PATH environment (either the user's path or the system path, depending on the installation type selected).
Refs beeware/briefcase#1781
Refs beeware/briefcase#1850
=> Add support for Console apps

.github/workflows/update-binary.yml, stub/pyproject.toml
Migrate the binary tagging code from the app repo.
Refs beeware/briefcase-windows-app-template#53
=> Add code to tag, build and publish stub binaries.

.github/workflows/ci.yml, .github/workflows/update-binary.yml, {{ cookiecutter.format }}/briefcase.toml
- Drop Python 3.8 as Briefcase's `main` branch no longer supports it
=> Drop Python 3.8 support

.github/workflows/ci.yml, .github/workflows/update-binary.yml, {{ cookiecutter.format }}/briefcase.toml
- Add Python 3.13.0
- Bump 3.12.5 -> 3.12.7
=> Add support for Python 3.13

{{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/Main.cpp
Fixes #47.
Implements the same fix as beeware/briefcase-macOS-Xcode-template#65, with some additional refactoring of some common C++ String creation code.
=> Allow for runpy returning non-integer results.

{{ cookiecutter.format }}/briefcase.toml
Adds `python.exe` and `pythonw.exe` to the default cleanup list for Window apps. 
This is required because command line installs add the app directory to the path; this means `python.exe` becomes visible (and may be preferred over other Python installs on a system).
Refs beeware/briefcase#2139.
=> Cleanup raw python executables.

cookiecutter.json, {{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
Copied changes from beeware/briefcase-windows-app-template#62
This PR adds file associations to Windows apps. The support in briefcase.toml is already there and the feature is documented. It wasn't yet implemented for Windows, however.
Refs beeware/briefcase#1706 (corrects the problem for Windows).
=> Add file associations

{{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/Main.cpp
eschew log rotation strategy. no longer rotating, but just putting timestamp on filename. this will attempt to clean up older files as well.
Previously, if existing files were still open because multiple executables were running, the deletion strategy would attempt to delete and fail, which would prevent the app from running multiple times.  Now, the logs aren't being rotated. Instead, they have a timestamp in the filename, and are deleted based on their age.  This does allow multiple runs to happen concurrently.  
Example:
=> replace log rotation with timestamped log files and cleanup by age

cookiecutter.json, {{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
Provide the extension point allowing the Start menu item installed by Briefcase to point at an arbitrary path in the packaged bundle.
Refs beeware/briefcase#2333
Refs beeware/briefcase-windows-app-template#66
briefcase-repo: https://github.com/freakboy3742/briefcase.git
briefcase-ref: non-briefcase-package
=> Add handling for customized external binaries.

.github/workflows/ci.yml, .github/workflows/update-binary.yml, {{ cookiecutter.format }}/briefcase.toml, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/Main.cpp, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/packages.config, {{ cookiecutter.format }}/{{ cookiecutter.formal_name }}/{{ cookiecutter.formal_name }}.vcxproj
Python 3.9 is EOL; 3.14 is now available.
Also includes the fix for locale initialization (see beeware/briefcase-iOS-Xcode-template#57).
This will require re-tagging of the binaries to generate the first 3.14 binary.
Needs an update when 3.14.0 final is available.
~~Requires beeware/briefcase#2432 for the 3.14 tests to pass.~~
Requires beeware/briefcase#2433 for the 3.14 tests to pass.
briefcase-repo: https://github.com/freakboy3742/briefcase
briefcase-ref: nuget-filter
=> Drop Python 3.9, add 3.14.

{{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
Change the template to prevent descriptions longer than 256 chars 
Fix for [briefcase truncated icon issue](https://github.com/beeware/briefcase/issues/2465)
=> Ttruncate description if larger than 256 chars

cookiecutter.json, {{ cookiecutter.format }}/{{ cookiecutter.app_name }}.wxs
Adds XMLEscape extension to author name usage in {{ cookiecutter.app_name }}.xws
Partially fixes [beeware/briefcase#2103](https://github.com/beeware/briefcase/issues/2103)
=> [2103] fix: Adds author xml escaping
